---
substitutions:
  device_name: bedroom-job-rocket
  system_name: bedroom-job-rocket
  device_description: "WS2812 job status LEDs - slaapkamer"
  friendly_name: "Bedroom Job Rocket"
  ap_ssid: "Job Rocket AP"

packages:
  device: !include devices/bedroom-job-rocket-atom-lite.yaml
