---
substitutions:
  system_name: bedroom-job-rocket
  host_name: bedroom-job-rocket.home.econline.nl
  device_description: "WS2812 wake-up alarm light - bedroom"
  friendly_name: "Bedroom Job Rocket"

packages:
  device: !include m5stack-atom-lite/base.yaml
