---
substitutions:
  system_name: downstairs-hallway-waterp1meter
  host_name: downstairs-hallway-waterp1meter-esp.home.econline.nl
  friendly_name: Downstairs Hallway - WaterP1Meter
  device_description: Custom ESP that sends water meter and smart meter data

packages:
  device: !include
    file: waterp1meterkit-v3/base.yaml
    vars:
      gas_mbus_id: "2"