---
substitutions:
  device_name: kitchen-nspanel
  host_name: kitchen-nspanel-esp.home.econline.nl
  friendly_name: Kitchen - NSPanel
  device_description: Smart touchscreen for home automation, integrates with Home Assistant.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_pwd
  ota_password: !secret ota_password
  language: en      # Language code - see docs/localization.md for all supported codes
  boot_sound: false
  # Add-on configuration (if needed)
  ## Upload TFT
  upload_tft_automatically: true
  ## Climate add-on
  # heater_relay: "1"  # Possible values: "1" or "2"

packages:
  device: !include sonoff-nspanel/base.yaml
