---
substitutions:
  system_name: kitchen_nspanel
  host_name: kitchen-nspanel-esp.home.econline.nl
  friendly_name: Kitchen - NSPanel
  device_description: Smart touchscreen for home automation, integrates with Home Assistant.

packages:
  device: !include sonoff-nspanel/base.yaml
