---
# Device: M5Stack Atom Lite (ESP32)
# https://docs.platformio.org/en/stable/boards/espressif32/m5stack-core-esp32.html

esp32:
  board: m5stack-atom
  framework:
    type: arduino

packages:
  common: !include ../esphome-common/base.yaml
  wifi: !include ../esphome-common/wifi.yaml
