---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Amsterdam"
  time_update_interval: 6h

time:
  - <<: !include ../time/sntp.yaml
    timezone: "${time_timezone}"
    update_interval: ${time_update_interval}
