---
# Device: CloudFree EU Plug (P1EU)
# Config is based on https://www.esphome-devices.com/devices/CloudFree-EU-Plug-(P1EU)
#

substitutions:
  # Higher value gives lower watt readout
  current_res: "${current_res}"
  # Lower value gives lower voltage readout
  voltage_div: "${voltage_div}"

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/esp_01.yaml

sensor:
  # Reports the Current, Voltage, and Power used by the plugged-in device
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 8
    update_interval: 10s
    current:
      name: ${friendly_name} Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      id: wattage
      name: ${friendly_name} Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}

  # Reports the total Power so-far each day, resets at midnight, see https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  # Button on the front is pressed and then toggle relay
  - platform: gpio
    device_class: power
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Button # Name to make button visible in HA
    on_press:
      - switch.toggle: relay

switch:
  # Relay itself
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO15
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: # Action when relay is turned on
      - script.execute: led_power_on
    on_turn_off: # Action when relay is turned off
      - script.execute: led_relay_off

output:
  # Output GPIOs for blue led
  - platform: esp8266_pwm # Blue
    id: output_blue_led
    pin:
      number: GPIO02
      inverted: true

light:
  # RGB light
  - platform: monochromatic
    name: ${friendly_name} Light
    output: output_blue_led
    id: light_blue_led

# Blink the blue light if we aren't connected to WiFi. Could use https://esphome.io/components/status_led.html instead but then we couldn't use the blue light for other things as well.
# Only if not connected after 30s
interval:
  - interval: 2000ms
    then:
      - if:
          condition:
            for:
              time: 30s
              condition:
                not:
                  wifi.connected:
          then:
            - light.turn_on:
                id: light_blue_led
                brightness: 100%

script:
  - id: led_relay_off # Normal operation when relay is off
    then:
      - light.turn_off:
          id: light_blue_led
  - id: led_power_on # Normal operation when relay is on
    then:
      - light.turn_on:
          id: light_blue_led
          brightness: 80%
