# Device: Enri.nl P1 Shield v2
# Config is based on https://github.com/aiolos/ESPHome-config/blob/main/p1-with-gas.yaml
#

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/esp_01.yaml

substitutions:
  dsmr_output_port: "8088"

external_components:
  - source: github://oxan/esphome-stream-server

uart:
  - id: uart_bus
    rx_pin: RX
    baud_rate: 115200
    rx_buffer_size: 1024

stream_server:
  id: ss
  uart_id: uart_bus
  port: ${dsmr_output_port}
