---
# Device: M5Stack Atom Speaker Kit
# Config is based on https://github.com/esphome/media-players/blob/main/m5stack-atom-speaker-kit.yaml
#

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/m5stack-atom.yaml

substitutions:
  log_baudrate: "115200"

globals:
  - id: var_chime_muted
    type: bool
    restore_value: true
    initial_value: "false"

improv_serial:

i2s_audio:
  - i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${friendly_name} Button

light:
  - platform: fastled_clockless
    name: ${friendly_name}
    id: led
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    on_turn_on:
      then:
        - light.turn_on:
            id: led
            brightness: 30%
            red: 0%
            green: 100%
            blue: 0%

switch:
  - platform: template
    name: "${friendly_name} Muted"
    id: doorbell_chime_muted
    restore_mode: DISABLED
    turn_on_action:
      - globals.set:
          id: var_chime_muted
          value: "true"
    turn_off_action:
      - globals.set:
          id: var_chime_muted
          value: "false"
    lambda: |-
      return id(var_chime_muted);
