---
# Device: Shelly 1
# Config is based on https://www.esphome-devices.com/devices/Shelly-1
#

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/esp_01.yaml

# Output to toggle the relay
output:
  - platform: gpio
    pin: GPIO4
    id: device_relay

# Take the output and exposes it as a light
light:
  - platform: binary
    name: "${friendly_name}"
    output: device_relay
    restore_mode: RESTORE_DEFAULT_OFF
    id: lightid

# Take the light and exposes it as a switch
switch:
  - platform: template
    name: "${friendly_name}"
    lambda: |-
      return id(lightid).current_values.get_state() > 0;
    turn_on_action:
      - light.turn_on: lightid
    turn_off_action:
      - light.turn_on: lightid

# Binary sensor for the physical button press
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      # mode: INPUT_PULLUP
      # inverted: True
    name: "${friendly_name} Button"
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: device_button
