---
# Device: Tuya smart valve
#

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/esp_12e.yaml

# Exposed switches.
switch:
  # Switch to restart the doorbell.
  - platform: restart
    name: ${friendly_name} Restart

# exposed lights.
light:
  - platform: rgb
    name: ${friendly_name} Light
    icon: mdi:star-shooting
    id: rgb_light
    red: red
    green: green
    blue: blue
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 2s
    effects:
      - random:
          name: Random
          transition_length: 5s
          update_interval: 5s
      - random:
          name: Random Slow
          transition_length: 10s
          update_interval: 5s
    on_turn_on:
      then:
        - light.turn_on: btn_led
    on_turn_off:
      then:
        - light.turn_off: btn_led

  - platform: monochromatic
    name: ${friendly_name} Laser
    icon: mdi:laser-pointer
    id: laser
    output: laser_pwm
    restore_mode: ALWAYS_OFF
    default_transition_length: 3s

  - platform: monochromatic
    name: ${friendly_name} Button Led
    icon: mdi:led-outline
    entity_category: diagnostic
    id: btn_led
    output: btn_led_pwm
    restore_mode: ALWAYS_OFF

fan:
  platform: speed
  name: ${friendly_name} Motor
  icon: mdi:play-speed
  id: motor
  output: motor_pwm
  restore_mode: ALWAYS_OFF

output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO4
    inverted: true

  - platform: esp8266_pwm
    id: green
    pin: GPIO12
    inverted: true

  - platform: esp8266_pwm
    id: blue
    pin: GPIO14
    inverted: true

  - platform: esp8266_pwm
    id: laser_pwm
    pin: GPIO5
    inverted: true

  - platform: esp8266_pwm
    id: motor_pwm
    pin: GPIO13
    min_power: 15%
    max_power: 80%

  - platform: esp8266_pwm
    id: btn_led_pwm
    pin: GPIO15
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLDOWN_16
      inverted: true
    name: ${friendly_name} Button
    id: ${friendly_name}_button
    on_multi_click:
    # single click
    - timing:
          - ON for at most 1s
          - OFF for at least 0.350s
      then:
        - light.turn_on: 
            id: rgb_light
            brightness: 30%
        - light.turn_on: 
            id: laser
            brightness: 65%
        - delay : 1h
        - light.turn_off: 
            id: rgb_light
        - light.turn_off: 
            id: laser
    # double click
    - timing:
          - ON for at most 1s
          - OFF for at most 0.35s
          - ON for at most 1s
          - OFF for at least 0.35s
      then:
        - light.toggle: laser
    # hold
    on_press:
      then:
      - if:
          condition:
              lambda: |-
                return id(dim);
          then:
          - delay: 0.1s
          - while:
              condition:
                binary_sensor.is_on: ${friendly_name}_button
              then:
                - light.dim_relative:
                    id: rgb_light
                    relative_brightness: 5%
                - delay: 0.1s
          - lambda: |-
              id(dim) = (false);
          else:
          - delay: 0.1s
          - while:
              condition:
                binary_sensor.is_on: ${friendly_name}_button
              then:
                - light.dim_relative:
                    id: rgb_light
                    relative_brightness: 5%
                - delay: 0.1s
          - lambda: |-
              id(dim) = (true);
